# fly.toml app configuration file generated for onboarding-service-api on 2025-04-08T19:23:41+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onboarding-service-api'
primary_region = 'syd'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
