"""Make status a string

Revision ID: 2154ae66ad0f
Revises: 89524b5df642
Create Date: 2025-05-05 21:10:16.168305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2154ae66ad0f'
down_revision: Union[str, None] = '89524b5df642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_onboarding_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'complete', 'cancelled', name='employeeonboardingstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_onboarding_requests', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'in_progress', 'complete', 'cancelled', name='employeeonboardingstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
