"""update display_names to code

Revision ID: 244f272106c5
Revises: 3a7890627cdf
Create Date: 2025-04-18 11:06:00.736679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244f272106c5'
down_revision: Union[str, None] = '3a7890627cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('code', sa.String(), nullable=False))
    op.drop_column('applications', 'display_name')
    op.add_column('roles', sa.Column('code', sa.String(), nullable=False))
    op.drop_column('roles', 'display_name')
    op.add_column('templates', sa.Column('code', sa.String(), nullable=False))
    op.drop_column('templates', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('templates', 'code')
    op.add_column('roles', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('roles', 'code')
    op.add_column('applications', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('applications', 'code')
    # ### end Alembic commands ###
