"""remove unique constraint from names

Revision ID: 3a7890627cdf
Revises: 208df723f571
Create Date: 2025-04-18 10:31:36.493515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7890627cdf'
down_revision: Union[str, None] = '208df723f571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('applications_name_key', 'applications', type_='unique')
    op.create_unique_constraint(None, 'employees', ['id'])
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_constraint('templates_name_key', 'templates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('templates_name_key', 'templates', ['name'])
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_unique_constraint('applications_name_key', 'applications', ['name'])
    op.drop_column('applications', 'description')
    # ### end Alembic commands ###
