"""remove employee profile table and add role_id to employee onboarding

Revision ID: 3e869f27073d
Revises: 8930832e8f60
Create Date: 2025-05-04 15:36:01.475759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e869f27073d'
down_revision: Union[str, None] = '8930832e8f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_profiles')
    op.add_column('employee_onboardings', sa.Column('role_id', sa.UUID(), server_default='0d4941ae-f6ca-44fa-8b53-6588ee97e904', nullable=False))
    op.create_foreign_key(None, 'employee_onboardings', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_onboardings', type_='foreignkey')
    op.drop_column('employee_onboardings', 'role_id')
    op.create_table('employee_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='employee_profiles_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='employee_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='employee_profiles_pkey')
    )
    # ### end Alembic commands ###
