"""remove contacts and application contacts tables

Revision ID: 6df5d4a0768a
Revises: 70ce84aaede1
Create Date: 2025-05-26 20:23:52.489257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6df5d4a0768a"
down_revision: Union[str, None] = "70ce84aaede1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "employee_onboarding_requests_acknowledged_by_fkey",
        "employee_onboarding_requests",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "employee_onboarding_requests", "users", ["acknowledged_by"], ["id"]
    )
    op.drop_table("application_contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employee_onboarding_requests", type_="foreignkey")
    op.create_foreign_key(
        "employee_onboarding_requests_acknowledged_by_fkey",
        "employee_onboarding_requests",
        "contacts",
        ["acknowledged_by"],
        ["id"],
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("external_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("organisation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_updated_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name="contacts_organisation_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="contacts_pkey"),
        sa.UniqueConstraint("external_id", name="contacts_external_id_key"),
        sa.UniqueConstraint("id", name="contacts_id_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "application_contacts",
        sa.Column("application_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("contact_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name="application_contacts_application_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name="application_contacts_contact_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "application_id", "contact_id", name="application_contacts_pkey"
        ),
    )
    # ### end Alembic commands ###
