"""make started_by nullable

Revision ID: 8930832e8f60
Revises: 074f6f02ff0d
Create Date: 2025-05-02 16:58:26.966281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8930832e8f60'
down_revision: Union[str, None] = '074f6f02ff0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_onboardings', 'started_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_onboardings', 'started_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
