"""alter employeeonboardingrequestmodel

Revision ID: 97c1e3f75233
Revises: 3e869f27073d
Create Date: 2025-05-05 20:25:15.777062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c1e3f75233'
down_revision: Union[str, None] = '3e869f27073d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_onboarding_requests', sa.Column('employee_id', sa.UUID(), nullable=False))
    op.add_column('employee_onboarding_requests', sa.Column('acknowledged_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employee_onboarding_requests', 'users', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'employee_onboarding_requests', 'contacts', ['acknowledged_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_onboarding_requests', type_='foreignkey')
    op.drop_constraint(None, 'employee_onboarding_requests', type_='foreignkey')
    op.drop_column('employee_onboarding_requests', 'acknowledged_by')
    op.drop_column('employee_onboarding_requests', 'employee_id')
    # ### end Alembic commands ###
