"""Add first and last name to new_hires

Revision ID: 98ffbd4b36b8
Revises: 7201fa27166f
Create Date: 2025-04-12 12:42:54.794276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ffbd4b36b8'
down_revision: Union[str, None] = '7201fa27166f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_hires', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('new_hires', sa.Column('last_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'new_hires', ['id'])
    op.drop_column('new_hires', 'name')
    op.create_unique_constraint(None, 'roles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.add_column('new_hires', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'new_hires', type_='unique')
    op.drop_column('new_hires', 'last_name')
    op.drop_column('new_hires', 'first_name')
    # ### end Alembic commands ###
