"""add org_id foreign key to roles and users table

Revision ID: bc6ee2f693d9
Revises: ed40f56638ce
Create Date: 2025-04-13 15:18:54.531957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6ee2f693d9'
down_revision: Union[str, None] = 'ed40f56638ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organisations', ['id'])
    op.add_column('roles', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'roles', 'organisations', ['organisation_id'], ['id'])
    op.add_column('users', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organisation_id')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'organisation_id')
    op.drop_constraint(None, 'organisations', type_='unique')
    # ### end Alembic commands ###
