"""remove employee_id from onboarding requests model

Revision ID: bca52966c2b7
Revises: 24de8a9eca0e
Create Date: 2025-05-10 17:24:34.243209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca52966c2b7'
down_revision: Union[str, None] = '24de8a9eca0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_onboarding_requests_employee_id_fkey', 'employee_onboarding_requests', type_='foreignkey')
    op.drop_column('employee_onboarding_requests', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_onboarding_requests', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('employee_onboarding_requests_employee_id_fkey', 'employee_onboarding_requests', 'users', ['employee_id'], ['id'])
    # ### end Alembic commands ###
