"""remove 'code' from models

Revision ID: c90d50ff9ea6
Revises: d1501ec0546e
Create Date: 2025-06-04 22:18:55.072516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90d50ff9ea6'
down_revision: Union[str, None] = 'd1501ec0546e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'code')
    op.drop_column('roles', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
