"""add applcations and role_templates table

Revision ID: ccb8939411a5
Revises: 2c13ebda2338
Create Date: 2025-04-13 15:58:18.317522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb8939411a5'
down_revision: Union[str, None] = '2c13ebda2338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_templates',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'template_id')
    )
    op.create_unique_constraint(None, 'admins', ['id'])
    op.create_unique_constraint(None, 'contacts', ['id'])
    op.create_unique_constraint(None, 'templates', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_table('role_templates')
    op.drop_table('applications')
    # ### end Alembic commands ###
