"""add new role

Revision ID: eab2f7aaa168
Revises: 6df5d4a0768a
Create Date: 2025-05-26 20:34:23.050326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eab2f7aaa168"
down_revision: Union[str, None] = "6df5d4a0768a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE usertype ADD VALUE 'access_manager'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
