"""add updated and created date to all models

Revision ID: f29e6ce9b564
Revises: 613387afba05
Create Date: 2025-04-26 12:36:07.729000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29e6ce9b564'
down_revision: Union[str, None] = '613387afba05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('admins', sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('applications', sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('contacts', sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('employees', sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organisations', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organisations', sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'last_updated_date')
    op.drop_column('organisations', 'last_updated_date')
    op.drop_column('organisations', 'created_date')
    op.drop_column('employees', 'last_updated_date')
    op.drop_column('contacts', 'last_updated_date')
    op.drop_column('applications', 'last_updated_date')
    op.drop_column('admins', 'last_updated_date')
    op.drop_column('admins', 'created_date')
    # ### end Alembic commands ###
